name: âœ… CI
on:
  push:
  pull_request:
  schedule:
    - cron:  '0 12 10 * *' # Monthly at noon on the tenth
jobs:
  build:
    strategy:
      matrix:
        pg: [18, 17, 16, 15, 14, 13]
    name: ğŸ˜ PostgreSQL ${{ matrix.pg }}
    runs-on: ubuntu-latest
    container: pgxn/pgxn-tools
    steps:
      - run: pg-start ${{ matrix.pg }} libcurl4-openssl-dev
      - uses: actions/checkout@v4
        with: { submodules: true }
      - run: pg-build-test
