name: ğŸ˜ Postgres CI
on:
  push:
  pull_request:
  schedule:
    - cron:  '0 12 10 * *' # Monthly at noon on the tenth
jobs:
  build:
    strategy:
      matrix:
        pg: [18, 17, 16, 15, 14, 13]
        os:
          - { icon: ğŸ§, arch: amd64, on: ubuntu-latest }
          # - { icon: ğŸ§, arch: arm64, on: ubuntu-24.04-arm } # XXX
    name: ğŸ˜ PostgreSQL ${{ matrix.pg }} ${{ matrix.os.icon }} ${{ matrix.os.arch }}
    runs-on: ${{ matrix.os.on }}
    container: pgxn/pgxn-tools
    steps:
      - name: Start Postgres ${{ matrix.pg }}
        run: pg-start ${{ matrix.pg }} libcurl4-openssl-dev uuid-dev
      - name: Checkout the Repository
        uses: actions/checkout@v4
        with: { submodules: true }
      - name: Start ClickHouse
        run: .github/ubuntu/clickhouse.sh
      - name: Test DSO
        run: pg-build-test
      - name: Clean
        run: make clean
      - name: Test Static
        run: pg-build-test
        env: { CH_BUILD: static }
